const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/jairlinethai/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root = path.resolve(__dirname, '../src/SnapCraft/Assets');
(async () => {
  const server = http.createServer((req,res) => {
    const file = path.resolve(root, '.' + new URL(req.url,'http://localhost').pathname);
    if (!file.startsWith(root + path.sep) || !fs.existsSync(file)) return res.writeHead(404).end();
    res.setHeader('Content-Type', {'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'}[path.extname(file)] || 'application/octet-stream');
    fs.createReadStream(file).pipe(res);
  });
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  let browser;
  try {
    browser = await chromium.launch({headless:true});
    const page = await browser.newPage({viewport:{width:1300,height:900}});
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    const fixtures=await page.evaluate(()=>['#ff0000','#0000ff'].map(color=>{
      const c=document.createElement('canvas');c.width=300;c.height=200;
      const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,300,200);return c.toDataURL();
    }));
    await page.goto(`http://127.0.0.1:${server.address().port}/editor.html?image=${encodeURIComponent(fixtures[0])}`);
    await page.locator('#loading').waitFor({state:'hidden'});
    assert.equal(await page.evaluate(()=>typeof neoSnapEditor.exportProject),'function','Editor must export editable projects');
    const first=await page.evaluate(()=>{
      objects.push({tool:'text',x1:30,y1:30,text:'Editable',size:6,color:'#ffffff',opacity:1});render();return neoSnapEditor.exportProject().project;
    });
    const second=structuredClone(first);second.assets[0].dataUrl=fixtures[1];second.objects=[];
    await page.evaluate(async projects=>neoSnapEditor.combineProjects(projects,'vertical',12),[first,second]);
    assert.deepEqual(await page.evaluate(()=>[canvas.width,canvas.height]),[300,412]);
    assert.deepEqual(await page.evaluate(()=>{render(false);return [...ctx.getImageData(280,100,1,1).data,...ctx.getImageData(280,300,1,1).data]}),[255,0,0,255,0,0,255,255]);
    assert.equal(await page.evaluate(()=>objects.filter(o=>o.tool==='text')[0].text),'Editable');
    const saved=await page.evaluate(()=>neoSnapEditor.exportProject().project);
    const horizontal=await page.evaluate(async projects=>{await neoSnapEditor.combineProjects(projects,'horizontal',10);return [canvas.width,canvas.height];},[first,second]);
    assert.deepEqual(horizontal,[610,200]);
    await page.evaluate(p=>neoSnapEditor.loadProject(p),saved);
    await page.evaluate(()=>{
      selected=objects.findIndex(o=>o.tool==='image');
      const original=structuredClone(objects[selected]);checkpoint();
      gesture={children:prepareImageChildren(objects[selected])};
      resizeItem(objects[selected],original,{x:150,y:100});gesture=null;render();
    });
    assert.equal(await page.evaluate(()=>objects.find(o=>o.tool==='text').size),3,'Image resize must scale editable text');
    assert.equal(await page.evaluate(()=>objects.find(o=>o.tool==='text').x1),15);
    await page.locator('#undoButton').click();
    await page.evaluate(()=>{
      selected=objects.findIndex(o=>o.tool==='image');setTool('crop');
      cropDraft={x:20,y:20,width:250,height:150};
    });
    await page.locator('#applyCrop').click();
    assert.deepEqual(await page.evaluate(()=>objects.find(o=>o.tool==='image').sourceCrop),{x:20,y:20,width:250,height:150});
    assert.deepEqual(await page.evaluate(()=>[canvas.width,canvas.height]),[300,412],'Per-image crop must not crop workspace');
    await page.locator('#undoButton').click();
    await page.evaluate(async p=>neoSnapEditor.loadProject(p),saved);
    assert.deepEqual(await page.evaluate(()=>neoSnapEditor.exportProject().project),saved,'Project must round-trip without flattening');
    const before=await page.evaluate(()=>neoSnapEditor.exportProject().project);
    await assert.rejects(page.evaluate(()=>neoSnapEditor.loadProject({format:'neo-snap',version:999})),/version|เวอร์ชัน|ไฟล์/);
    assert.deepEqual(await page.evaluate(()=>neoSnapEditor.exportProject().project),before,'Rejected import must leave work intact');
    const bad=structuredClone(saved);bad.assets[0].dataUrl='https://example.com/private.png';
    await assert.rejects(page.evaluate(p=>neoSnapEditor.loadProject(p),bad),/PNG|ไฟล์|ภาพ/);
    const invalid=structuredClone(saved);invalid.objects[0].x1=null;
    await assert.rejects(page.evaluate(p=>neoSnapEditor.loadProject(p),invalid),/ตำแหน่ง|วัตถุ/);
    assert.deepEqual(await page.evaluate(()=>neoSnapEditor.exportProject().project),before);
    const invalidEffect=structuredClone(saved);invalidEffect.objects[0].shadow={enabled:true,color:'#000000',blur:'very large',x:0,y:0};
    await assert.rejects(page.evaluate(p=>neoSnapEditor.loadProject(p),invalidEffect),/เงา|วัตถุ|ไฟล์/);
    await page.evaluate(()=>{
      selected=objects.findIndex(o=>o.tool==='image');checkpoint();
      const old=structuredClone(objects[selected]);moveItem(objects[selected],old,0,10);render();
    });
    assert.equal(await page.evaluate(()=>objects.find(o=>o.tool==='text').y1),40,'Image movement carries editable annotations');
    await page.locator('#undoButton').click();
    assert.equal(await page.evaluate(()=>objects.find(o=>o.tool==='text').y1),30);
    await page.locator('#redoButton').click();
    assert.equal(await page.evaluate(()=>objects.find(o=>o.tool==='text').y1),40);
    await page.evaluate(()=>{selected=objects.findIndex(o=>o.tool==='image');removeSelected();});
    assert.equal(await page.evaluate(()=>objects.some(o=>o.tool==='text')),false,'Deleting an image deletes its owned annotations');
    await page.locator('#undoButton').click();
    assert.equal(await page.evaluate(()=>objects.some(o=>o.tool==='text')),true);
    await page.evaluate(()=>neoSnapEditor.loadProject(window.neoSnapEditor.exportProject().project));
    const temp=await page.evaluate(async url=>{await neoSnapEditor.addImages([url]);return objects.filter(o=>o.tool==='image').length;},fixtures[0]);
    assert.equal(temp,3);
    await page.locator('#undoButton').click();assert.equal(await page.evaluate(()=>objects.filter(o=>o.tool==='image').length),2);
    await page.evaluate(()=>neoSnapEditor.markKept(neoSnapEditor.exportProject().snapshot));
    assert.equal(await page.evaluate(()=>neoSnapEditor.hasUnkeptChanges()),false);
    await page.evaluate(()=>{objects.find(o=>o.tool==='text').text='Changed';render();});
    assert.equal(await page.evaluate(()=>neoSnapEditor.hasUnkeptChanges()),true,'Editing after project save must warn again');
    assert(await page.locator('#combineButton svg').count(),'New toolbar icons must render');
    await page.evaluate(()=>neoSnapEditor.resizeWorkspace(650,500));
    assert.deepEqual(await page.evaluate(()=>[canvas.width,canvas.height]),[650,500],'Workspace can grow for manual arrangement');
    await page.locator('#undoButton').click();
    assert.deepEqual(await page.evaluate(()=>[canvas.width,canvas.height]),[300,412]);
    await page.locator('#imageFiles').setInputFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from(fixtures[0].split(',')[1],'base64')});
    await page.waitForFunction(()=>objects.filter(o=>o.tool==='image').length===3);
    assert.equal(await page.evaluate(()=>neoSnapEditor.exportProject().project.assets.length),2,'Repeated imports must reuse embedded source assets');
    await page.locator('#undoButton').click();
    assert.deepEqual(errors,[]);
    fs.mkdirSync(path.resolve(__dirname,'../dist/project-preview'),{recursive:true});
    await page.screenshot({path:path.resolve(__dirname,'../dist/project-preview/workspace.png')});
    await page.setViewportSize({width:800,height:600});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Toolbar must fit narrow editor');
    await page.setViewportSize({width:480,height:700});
    const header=await page.locator('#combineButton').boundingBox(),brand=await page.locator('.brand-link').boundingBox();
    assert(header.y>=brand.y+brand.height,'Narrow toolbar actions must not overlap branding');
    await page.screenshot({path:path.resolve(__dirname,'../dist/project-preview/workspace-narrow.png')});
    console.log('PASS editable projects: native pixels, combine, round-trip, safe rejection, owners, undo/redo, imports, layout');
  } finally {await browser?.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
