const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/jairlinethai/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const roots = [path.resolve(__dirname, '../src/SnapCraft/Assets'), ...(process.argv.includes('--windows-only') ? [] : [path.resolve(__dirname, '../../../outputs/chrome-capture-extension')])];

(async () => {
  const names = new Set();
  for (const root of roots) {
    for (const file of fs.readdirSync(root).filter((file) => /\.(html|js)$/.test(file))) {
      for (const match of fs.readFileSync(path.join(root, file), 'utf8').matchAll(/data-lucide=["']([\w-]+)["']/g)) names.add(match[1]);
    }
  }
  const exports = [...names].sort().map((name) => {
    const symbol = name.replace(/(^|-)(\w)/g, (_, dash, letter) => letter.toUpperCase());
    return `export { default as ${symbol} } from './icons/${name}.js';`;
  }).join('\n');
  const bundle = await esbuild.build({
    stdin: { contents: "import {createIcons, icons} from 'lucide'; globalThis.lucide = {createIcons: (options = {}) => createIcons({icons, ...options})};", resolveDir: __dirname },
    bundle: true, minify: true, write: false, format: 'iife',
    banner: { js: '/* Lucide 0.468.0 - ISC license. Generated by tools/build-assets.cjs. */' },
    plugins: [{ name: 'used-icons', setup(build) {
      build.onLoad({ filter: /iconsAndAliases\.js$/ }, (args) => ({ contents: exports, resolveDir: path.dirname(args.path), loader: 'js' }));
    } }]
  });
  for (const root of roots) fs.writeFileSync(path.join(root, 'vendor/lucide.js'), bundle.outputFiles[0].contents);
  console.log(`Lucide: ${names.size} icons, ${bundle.outputFiles[0].contents.length} bytes`);
  if (process.argv.includes('--icons-only')) return;
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    const svg = fs.readFileSync(path.join(roots[0], 'icons/icon.svg'));
    const pngs = [];
    for (const size of [16, 32, 48, 128, 256]) {
      await page.setContent(`<style>body{margin:0}</style><img width="${size}" height="${size}" src="data:image/svg+xml;base64,${svg.toString('base64')}">`);
      await page.locator('img').evaluate((img) => img.decode());
      const png = await page.screenshot({ clip: { x: 0, y: 0, width: size, height: size }, omitBackground: true });
      pngs.push({ size, png });
      if (size <= 128) for (const root of roots) fs.writeFileSync(path.join(root, `icons/icon-${size}.png`), png);
    }
    const header = Buffer.alloc(6 + pngs.length * 16);
    header.writeUInt16LE(1, 2); header.writeUInt16LE(pngs.length, 4);
    let offset = header.length;
    pngs.forEach(({ size, png }, index) => {
      const at = 6 + index * 16;
      header[at] = header[at + 1] = size % 256;
      header.writeUInt16LE(1, at + 4); header.writeUInt16LE(32, at + 6);
      header.writeUInt32LE(png.length, at + 8); header.writeUInt32LE(offset, at + 12);
      offset += png.length;
    });
    fs.writeFileSync(path.join(roots[0], 'icons/app.ico'), Buffer.concat([header, ...pngs.map((item) => item.png)]));
    await page.setContent('<style>body{margin:0}svg{width:20px;height:20px;color:#46617d}</style><i data-lucide="x"></i>');
    await page.addScriptTag({ content: bundle.outputFiles[0].text });
    await page.evaluate(() => lucide.createIcons());
    fs.writeFileSync(path.join(roots[0], 'icons/close.png'), await page.screenshot({ clip: { x: 0, y: 0, width: 20, height: 20 }, omitBackground: true }));
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
